GET http://localhost:8000/api/v1/users

###

POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
    "username":"Bidur",
    "password":"password"
}

###

POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "name":"Bidur",
    "password":"passwod"
}

###

POST http://localhost:8000/api/v1/products
Content-Type: application/json

{
    "productName":"kettle",
    "description":"jdnfjknakjd",
    "price":"45"
}

###
GET http://localhost:8000/api/v1/products
Content-Type: application/json

###
GET http://localhost:8000/api/v1/products/1
Content-Type: application/json

