GET http://localhost:8000/api/v1/users

###

POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
    "username":"admin",
    "password":"admin123"
}

###

POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "name":"admin",
    "password":"admin123"
}

###

POST http://localhost:8000/api/v1/products
Content-Type: application/json

{
    "productName":"iron",
    "description":"iron as",
    "price":"45"
}

###
GET http://localhost:8000/api/v1/products
Content-Type: application/json

###
GET http://localhost:8000/api/v1/products/1
Content-Type: application/json

